databases:
  - name: timesheetApi
    plan: free
    databaseName: timesheetDB
    user: PierreDugue

services:
  - type: web
    plan: free
    name: timesheetApi
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn timesheetApi.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: timesheetDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4