databases:
  - name: childcare-timesheet-api-db
    plan: free
    databaseName: timesheetdb_hc1z
    user: pierredugue

services:
  - type: web
    plan: free
    name: childcare-timesheet-api
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn childcare-timesheet-api.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: timesheetdb_hc1z
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4